//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsuranceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> CarYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public Nullable<bool> DUI { get; set; }
        public Nullable<int> Tickets { get; set; }
        public string CoverageType { get; set; }
        public Nullable<decimal> MonthlyQuote
        {
            get
            {
                decimal monthly = 50m;
                if (DateOfBirth > DateTime.Now.AddYears(-25)) monthly += 25;
                if (DateOfBirth > DateTime.Now.AddYears(-18)) monthly += 100;
                if (DateOfBirth < DateTime.Now.AddYears(-100)) monthly += 25;

                if (CarYear < 2000) monthly += 25;
                if (CarYear > 2015) monthly += 25;
                if (CarMake == "Porsche") monthly += 25;
                if (CarMake == "Porsche" && CarModel == "911 Carrera") monthly += 25;

                monthly += Convert.ToDecimal(25 * Tickets);

                if (Convert.ToBoolean(DUI)) monthly += (.25m * monthly);

                if (CoverageType == "Full") monthly += (.5m * monthly);

                return monthly;

            }
            set { }
        }
        public Nullable<decimal> YearlyQuote
        {
            get
            {
                return (12 * MonthlyQuote);
            }
            set { }
        }

        public string EmailAddress { get; set; }
    }
}
